apiVersion: apps/v1
kind: Deployment
metadata:
  name: kenya-gdp-app
  labels:
    app: kenya-gdp-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kenya-gdp-app
  template:
    metadata:
      labels:
        app: kenya-gdp-app
    spec:
      containers:
      - name: kenya-gdp-app
        image: ghcr.io/YOUR_USERNAME/kenya-gdp-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 15
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      volumes:
      - name: data-volume
        configMap:
          name: kenya-gdp-data